import { CONTRADICTION_TRIGGER_THRESHOLD, FRAGILITY_TRIGGER_THRESHOLD } from "./orgPolicy.ts"
import type { RecommendationContext, RecommendationDef, RecommendationInstance } from "./orgTypes.ts"

export const RECOMMENDATIONS: RecommendationDef[] = [
  { id: "r01", title: "Clarify external scanning cadence", summary: "Set a simple rhythm for scanning external change.", description: "Establish a monthly forum to review market, policy and customer shifts.", layers: ["ENV", "SEN"], derivedLayers: ["MGT"], triggerRef: "TRIG_ENV_SEN_LOW", headlines: ["Keep context visible", "Reduce surprises"], shortReason: "External changes are not reviewed in a consistent cadence.", actionSteps: ["Assign scanning ownership", "Publish a monthly summary", "Link findings to planning decisions"], cta: "Start scanning cadence", maxScore: 0.65 },
  { id: "r02", title: "Strengthen signal triage", summary: "Improve how signals are prioritised.", description: "Define lightweight triage rules for incoming operational and customer signals.", layers: ["SEN", "EXE"], derivedLayers: ["MGT"], triggerRef: "TRIG_SEN_EXE_GAP", headlines: ["Prioritise the right issues", "Reduce rework"], shortReason: "Teams receive many signals but triage is uneven.", actionSteps: ["Create triage criteria", "Route signals by impact", "Review unresolved items weekly"], cta: "Set triage rules", maxScore: 0.7 },
  { id: "r03", title: "Improve delivery planning hygiene", summary: "Tighten scope and sequencing.", description: "Adopt a planning checklist for dependencies, capacity and risk before commitments are final.", layers: ["EXE", "PRO"], derivedLayers: ["MGT"], triggerRef: "TRIG_EXE_PRO_LOW", headlines: ["Plan with confidence", "Lower delivery churn"], shortReason: "Execution friction suggests planning assumptions vary by team.", actionSteps: ["Use one planning template", "Confirm dependency owners", "Run a weekly risk review"], cta: "Adopt planning checklist", maxScore: 0.68 },
  { id: "r04", title: "Document process ownership", summary: "Make ownership visible and current.", description: "Assign process owners and review key workflows each quarter.", layers: ["PRO", "COM"], derivedLayers: ["MGT"], triggerRef: "TRIG_PRO_COM_AMBIG", headlines: ["Reduce ambiguity", "Improve handovers"], shortReason: "Process ownership appears inconsistent across teams.", actionSteps: ["Map top ten workflows", "Name accountable owners", "Publish review dates"], cta: "Publish process ownership", maxScore: 0.7 },
  { id: "r05", title: "Standardise decision communication", summary: "Use a consistent decision note format.", description: "Capture decision, rationale, owner and next review date in one concise template.", layers: ["COM", "COL"], derivedLayers: ["CUL"], triggerRef: "TRIG_COM_COL_LOW", headlines: ["Communicate once clearly", "Improve cross team alignment"], shortReason: "Communication style varies and slows shared understanding.", actionSteps: ["Create decision note template", "Store notes in one place", "Review adoption monthly"], cta: "Roll out decision notes", maxScore: 0.72 },
  { id: "r06", title: "Run dependency clinics", summary: "Resolve cross team blockers earlier.", description: "Schedule a weekly clinic for dependency risks and handover timing.", layers: ["COL", "EXE"], derivedLayers: ["CUL"], triggerRef: "TRIG_COL_EXE_BLOCKERS", headlines: ["Surface blockers early", "Improve flow"], shortReason: "Dependencies are often addressed late in delivery cycles.", actionSteps: ["Track top dependencies", "Set clear escalation rules", "Close actions in one week"], cta: "Launch dependency clinic", maxScore: 0.7 },
  { id: "r07", title: "Refresh engagement touchpoints", summary: "Increase quality of manager check ins.", description: "Introduce focused check in prompts on priorities, workload and support.", layers: ["ENG", "LDR"], derivedLayers: ["CUL"], triggerRef: "TRIG_ENG_LDR_LOW", headlines: ["Support healthy pace", "Strengthen trust"], shortReason: "Engagement feedback indicates uneven people support routines.", actionSteps: ["Publish check in prompts", "Train managers on follow through", "Review outcomes quarterly"], cta: "Improve check ins", maxScore: 0.68 },
  { id: "r08", title: "Consolidate core tools", summary: "Reduce avoidable tool switching.", description: "Prioritise a smaller set of core tools for planning, communication and reporting.", layers: ["TOO", "PRO"], derivedLayers: ["MGT"], triggerRef: "TRIG_TOO_PRO_FRICTION", headlines: ["Simplify daily work", "Improve data consistency"], shortReason: "Tool overlap is creating process and data friction.", actionSteps: ["Audit duplicate tooling", "Select core platform set", "Plan migration by team"], cta: "Consolidate tools", maxScore: 0.72 },
  { id: "r09", title: "Align leadership messages", summary: "Coordinate leadership narratives.", description: "Prepare shared talking points for strategy, priorities and trade offs.", layers: ["LDR", "COM"], derivedLayers: ["CUL"], triggerRef: "TRIG_LDR_COM_SPLIT", headlines: ["One clear direction", "Lower message drift"], shortReason: "Leadership messages appear to vary by channel.", actionSteps: ["Agree monthly message map", "Use common briefing notes", "Monitor understanding"], cta: "Align leadership narrative", maxScore: 0.7 },
  { id: "r10", title: "Link talent plans to demand", summary: "Connect skill planning to delivery needs.", description: "Review capability demand quarterly and align hiring and development priorities.", layers: ["TAL", "EXE"], derivedLayers: ["MGT"], triggerRef: "TRIG_TAL_EXE_CAPACITY", headlines: ["Match capability to demand", "Improve delivery confidence"], shortReason: "Capability plans and delivery demand are not fully aligned.", actionSteps: ["Forecast skills demand", "Prioritise critical roles", "Track skill development progress"], cta: "Update talent plan", maxScore: 0.7 },
  { id: "r11", title: "Improve regulated workflow readiness", summary: "Embed compliance checkpoints early.", description: "For regulated contexts, add practical checkpoints within routine planning and release flow.", layers: ["ENV", "PRO", "LDR"], derivedLayers: ["MGT"], triggerRef: "TRIG_REGULATED_READINESS", headlines: ["Reduce late compliance issues", "Increase predictability"], shortReason: "Compliance checks may be occurring too late in the cycle.", actionSteps: ["Define mandatory checkpoints", "Assign control owners", "Review findings monthly"], cta: "Embed compliance checkpoints", maxScore: 0.75 },
  { id: "r12", title: "Improve shift handover clarity", summary: "Strengthen information flow between shifts.", description: "Use a standard handover note to capture status, risks and next actions.", layers: ["COM", "COL", "EXE"], derivedLayers: ["CUL"], triggerRef: "TRIG_SHIFT_HANDOVER", headlines: ["Safer handovers", "Better continuity"], shortReason: "Shift based teams need clearer continuity information.", actionSteps: ["Create one handover template", "Timebox handover briefings", "Audit quality fortnightly"], cta: "Standardise handovers", maxScore: 0.73 },
  { id: "r13", title: "Improve remote coordination rituals", summary: "Support remote first alignment.", description: "Set explicit remote rituals for weekly planning, status and decisions.", layers: ["COL", "COM", "TOO"], derivedLayers: ["CUL"], triggerRef: "TRIG_REMOTE_COORDINATION", headlines: ["Keep distributed teams aligned", "Reduce missed context"], shortReason: "Remote coordination points are currently inconsistent.", actionSteps: ["Publish weekly ritual map", "Use shared decision logs", "Review adherence monthly"], cta: "Define remote rituals", maxScore: 0.72 },
  { id: "r14", title: "Strengthen product discovery loop", summary: "Tighten product feedback integration.", description: "Bring customer insight, delivery metrics and leadership priorities into one review loop.", layers: ["ENV", "SEN", "EXE"], derivedLayers: ["MGT"], triggerRef: "TRIG_PRODUCT_DISCOVERY", headlines: ["Use evidence for prioritisation", "Improve delivery fit"], shortReason: "Feedback and delivery planning are not always linked.", actionSteps: ["Run monthly insight review", "Connect findings to roadmap", "Track decision outcomes"], cta: "Create discovery loop", maxScore: 0.69 },
  { id: "r15", title: "Support client delivery predictability", summary: "Create clear client commitment gates.", description: "Define readiness gates before confirming delivery dates and scope.", layers: ["EXE", "COM", "PRO"], derivedLayers: ["MGT"], triggerRef: "TRIG_CLIENT_DELIVERY", headlines: ["Set realistic commitments", "Protect delivery quality"], shortReason: "Client commitments may be confirmed without consistent readiness checks.", actionSteps: ["Define commitment gates", "Confirm assumptions in writing", "Review exceptions monthly"], cta: "Adopt commitment gates", maxScore: 0.7 },
  { id: "r16", title: "Increase confidence in system data", summary: "Improve trust in operational metrics.", description: "Document source of truth for key metrics and review data quality routinely.", layers: ["TOO", "SEN", "COM"], derivedLayers: ["MGT"], triggerRef: "TRIG_DATA_CONFIDENCE", headlines: ["Trust the numbers", "Improve decision quality"], shortReason: "Confidence in system data appears lower than desired.", actionSteps: ["Define metric ownership", "Track data quality defects", "Publish monthly data notes"], cta: "Improve data confidence", maxScore: 0.74 },
  { id: "r17", title: "Reduce contradiction risk", summary: "Align stated priorities with observed behaviour.", description: "Compare declared priorities with workload allocation and adjust where gaps appear.", layers: ["LDR", "EXE", "ENG"], derivedLayers: ["CUL"], triggerRef: "TRIG_CONTRADICTION", headlines: ["Align words and actions", "Increase organisational trust"], shortReason: "Diagnostic patterns suggest a gap between intent and practice.", actionSteps: ["Review priority trade offs", "Share rationale transparently", "Track corrective actions"], cta: "Address contradiction risk", maxScore: 0.76 },
  { id: "r18", title: "Mitigate fragility in critical paths", summary: "Strengthen resilience where dependencies are tight.", description: "Identify high risk dependency paths and introduce backup ownership and playbooks.", layers: ["COL", "PRO", "TOO"], derivedLayers: ["MGT"], triggerRef: "TRIG_FRAGILITY", headlines: ["Improve resilience", "Protect critical outcomes"], shortReason: "Dependency fragility appears elevated in key workflows.", actionSteps: ["Map critical paths", "Assign backup owners", "Test response playbooks"], cta: "Reduce fragility", maxScore: 0.75 },
  { id: "r19", title: "Reinforce capability onboarding", summary: "Help new joiners become productive sooner.", description: "Create role based onboarding maps linking tools, processes and key contacts.", layers: ["TAL", "PRO", "TOO"], derivedLayers: ["CUL"], triggerRef: "TRIG_ONBOARDING", headlines: ["Speed up onboarding", "Improve consistency"], shortReason: "Capability ramp up may vary too much between teams.", actionSteps: ["Define role based onboarding packs", "Assign onboarding buddies", "Measure readiness at 30 days"], cta: "Improve onboarding", maxScore: 0.71 },
  { id: "r20", title: "Build a practical continuous improvement loop", summary: "Create a steady improvement habit.", description: "Set a monthly cycle to review evidence, choose actions and track outcomes.", layers: ["SEN", "PRO", "LDR"], derivedLayers: ["MGT", "CUL"], triggerRef: "TRIG_CONTINUOUS_IMPROVEMENT", headlines: ["Improve steadily", "Use evidence with confidence"], shortReason: "Improvement activity appears sporadic rather than routine.", actionSteps: ["Review evidence monthly", "Prioritise two actions", "Measure impact after one cycle"], cta: "Start improvement loop", maxScore: 0.78 },
]

export function selectRecommendations(ctx: RecommendationContext): RecommendationInstance[] {
  const scored = RECOMMENDATIONS.map((rec) => {
    const layerMean = rec.layers.reduce((sum, layer) => sum + ctx.effectiveScores[layer], 0) / rec.layers.length
    const scoreGate = (rec.maxScore === undefined || layerMean <= rec.maxScore) && (rec.minScore === undefined || layerMean >= rec.minScore)
    const triggerBoost = rec.triggerRef === "TRIG_CONTRADICTION" && ctx.meta.contradictionIndex >= CONTRADICTION_TRIGGER_THRESHOLD
      ? 0.3
      : rec.triggerRef === "TRIG_FRAGILITY" && ctx.meta.fragility >= FRAGILITY_TRIGGER_THRESHOLD
        ? 0.3
        : 0
    const rank = (1 - layerMean) * 0.7 + triggerBoost + (scoreGate ? 0.2 : -0.4)
    return { rec, rank }
  }).sort((a, b) => b.rank - a.rank)

  const chosen = scored.slice(0, 5)
  return chosen.map((item, idx) => ({
    id: item.rec.id,
    title: item.rec.title,
    summary: item.rec.summary,
    rationale: item.rec.shortReason ?? "Selected from current score pattern.",
    priority: idx < 3 ? "high" : "medium",
  }))
}
